import client from '@/api/client';
import { ApiResponse } from '@/types';

export const createCoursesApi = (
  studioId: number,
  staffId: number,
  classType: string,
  title: string,
  description: string,
  maxTrainee: number,
  minTrainee: number,
  startDate: string,
  endDate: string,
  bookingEndTime: string,
  bookingCancelEndTime: string,
  bookingChangeEndTime: string,
  hasMonClass: string,
  monClassStartTime: string,
  monClassEndTime: string,
  hasTueClass: string,
  tueClassStartTime: string,
  tueClassEndTime: string,
  hasWedClass: string,
  wedClassStartTime: string,
  wedClassEndTime: string,
  hasThuClass: string,
  thuClassStartTime: string,
  thuClassEndTime: string,
  hasFriClass: string,
  friClassStartTime: string,
  friClassEndTime: string,
  hasSatClass: string,
  satClassStartTime: string,
  satClassEndTime: string,
  hasSunClass: string,
  sunClassStartTime: string,
  sunClassEndTime: string,
): Promise<ApiResponse> =>
  client.post('/admin/course', {
    studioId,
    staffId,
    classType,
    title,
    description,
    maxTrainee,
    minTrainee,
    startDate,
    endDate,
    bookingEndTime,
    bookingCancelEndTime,
    bookingChangeEndTime,
    hasMonClass,
    monClassStartTime,
    monClassEndTime,
    hasTueClass,
    tueClassStartTime,
    tueClassEndTime,
    hasWedClass,
    wedClassStartTime,
    wedClassEndTime,
    hasThuClass,
    thuClassStartTime,
    thuClassEndTime,
    hasFriClass,
    friClassStartTime,
    friClassEndTime,
    hasSatClass,
    satClassStartTime,
    satClassEndTime,
    hasSunClass,
    sunClassStartTime,
    sunClassEndTime,
  });
